[
  {
    character: 'Iron Man',
    realname: 'Anthony Edward Stark (Tony)',
    species: 'Enhanced',
    status: 'Deceased',
    image: '',
    id: '1',
  },
  {
    character: 'Mighty Thor',
    realname: 'Thor Odinson',
    species: 'Non Human',
    status: 'Alive',
    image: '',
    id: '2',
  },
  {
    character: 'Captain America',
    realname: 'Steven Grant Rogers',
    species: 'Enhanced',
    status: 'Alive',
    image: '',
    id: '3',
  },
  {
    character: 'The Hulk',
    realname: 'Robert Bruce Banner',
    species: 'Enhanced',
    status: 'Alive',
    image: '',
    id: '4',
  },
  {
    character: 'Black Widow',
    realname: 'Natalia Alianovna Romanoff (Natasha)',
    species: 'Human',
    status: 'Deceased',
    image: '',
    id: '5',
  },
  {
    character: 'Hawkeye',
    realname: 'Clinton Francis Barton',
    species: 'Human',
    status: 'Alive',
    image: '',
    id: '6',
  },
  {
    character: 'Spider-Man',
    realname: 'Peter Benjamin Parker',
    species: 'Enhanced',
    status: 'Alive',
    image: '',
    id: '7',
  },
  {
    character: 'Black Panther',
    realname: "T'Challa",
    species: 'Enhanced',
    status: 'Deceased',
    image: '',
    id: '8',
  },
  {
    character: 'Ant-Man',
    realname: 'Scott Edward Harris Lang',
    species: 'Human',
    status: 'Alive',
    image: '',
    id: '9',
  },
  {
    character: 'The Wasp',
    realname: 'Hope van Dyne',
    species: 'Human',
    status: 'Alive',
    image: '',
    id: '10',
  },
  {
    character: 'Dr. Strange',
    realname: 'Stephen Vincent Strange',
    species: 'Human',
    status: 'Alive',
    image: '',
    id: '11',
  },
  {
    character: 'Captain Marvel',
    realname: 'Carol Susan Jane Danvers',
    species: 'Enhanced',
    status: 'Alive',
    image: '',
    id: '12',
  },
  {
    character: 'The Falcon / Captain America',
    realname: 'Samuel Thomas Wilson',
    species: 'Human',
    status: 'Alive',
    image: '',
    id: '13',
  },
  {
    character: 'Vision',
    realname: 'Vision',
    species: 'Non Human',
    status: 'Unknown',
    image: '',
    id: '14',
  },
  {
    character: 'Scarlet Witch',
    realname: 'Wanda Maximoff',
    species: 'Enhanced',
    status: 'Unknown',
    image: '',
    id: '15',
  },
  {
    character: 'Star-Lord',
    realname: 'Peter Jason Quill',
    species: 'Enhanced',
    status: 'Alive',
    image: '',
    id: '16',
  },
  {
    character: 'Gamora',
    realname: 'Gamora Zen Whoberi Ben Titan',
    species: 'Non Human',
    status: 'Deceased',
    image: '',
    id: '17',
  },
  {
    character: 'Rocket Racoon',
    realname: '89P13',
    species: 'Non Human',
    status: 'Alive',
    image: '',
    id: '18',
  },
  {
    character: 'Groot',
    realname: 'Groot',
    species: 'Non Human',
    status: 'Alive',
    image: '',
    id: '19',
  },
  {
    character: 'Drax The Destroyer',
    realname: 'Drax',
    species: 'Non Human',
    status: 'Alive',
    image: '',
    id: '20',
  },
];
